### ISSUE TITLE
Bumper sensor in navigation

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot_apps#1]
They added bump sensors to the navigation recently in 339f3dbf6726109460e2483906fd730f76a63151

Check it out for kobuki, we probably need to be publishing something here.

**Comment by corot** [comment]
I cannot find the code that publish bumper events as pointclouds. I sent an e-mail to the commiter

**Comment by corot** [comment]
I'm still waiting for the turtlebot code, but our version is ready

**Comment by stonier** [comment]
Catch up with me this morning - need a couple of fixes to the bump code in kobuki - in particular the aboslute topic name needs to be made non-absolute.

**Comment by corot** [comment]
did it!
