### ISSUE TITLE
Move kinect.launch into minimal.launch temporarily

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot_apps#10]
Move this out of the launchers (document which ones here) and put into minimal.launch so we can demo while kinect is being so unstable.

**Comment by LucidOne** [comment]
Did you see rosmetalaunch? It cycles through the launch files
in /etc/ros/launch.d and starts them. Perhaps that should be enabled by
default.

**Comment by stonier** [comment]
Problem is though, the apps (android paired apps) are all starting kinect on the assumption it isn't bootstrapped. They'll all fall over if kinect is already launched. We just need to temporarily fix something so we aren't embarassed by openni dropping out on us so often in the middle of a demo.

**Comment by stonier** [comment]
- Comment all the kinect.launch includes in the apps (these get automatically called from android)
- minimal_plus_kinect launcher

**Comment by jihoonl** [comment]
minimal_3dsensor.launch added in turtlebot_bringup/launch fb3213f5c91bb1741b938e170b8bbfa2ec6b12b5

**Comment by jihoonl** [comment]
Tested(DONE)
