### ISSUE TITLE
Indigo release?

### ISSUE THREAD

**Issue by trainman419** [turtlebot/turtlebot_apps#120]
The project I'm working on requires that the turtlebot_apps stack be released into Indigo. How can I help make the release process go more quickly?

It looks like this will also require releases of the `turtelbot_create` and `turtlebot` stacks, and is probably related to https://github.com/turtlebot/turtlebot/issues/139

**Comment by trainman419** [comment]
Bump. Is there anything I can do to help out here?

**Comment by stonier** [comment]
We were mostly waiting on time to put in capabilities and have a working rosjava on indigo but have been short on time. What we should probably do is start getting it out the door and insert those things as they arrive.

@jihoonl lets write an issue with a taks list of todos necessary for immediate release first thing next week. Austin can get involved there. Can also add him to some of these repos and the release repos as needed.

Austin ill link you to the task list issue from here once we have created it.

We did actually talk about writing news docs and doing releases two days ago. Been a bit quiet on that front lately.

**Comment by stonier** [comment]
@trainman419 I reinvigorated the indigo release schedule  meta-issue in https://github.com/turtlebot/turtlebot/issues/170. Also added you to the releasers repo so we can get started. Actually not too much to do to get a non-create/non-android release out there.

Closing here.
