### ISSUE TITLE
Issue with pano_py

### ISSUE THREAD

**Issue by ccard** [turtlebot/turtlebot_apps#121]
I am having a similar issue to [bit-pirate](https://github.com/turtlebot/turtlebot_apps/issues/66) and i made sure that I have the correct version of python installed and that didn't fix it.  I have looked extensively online and can't find a solution to this issue and I was wondering if you may have a solution. I am using ros indigo. My stake trace is bellow:

```
.../turtlebot/src/turtlebot_apps/software/pano/pano_py/src/pano_cv/opencv.cpp: In function ‘cv::Mat pano_py::{anonymous}::convert_from_cvmat(PyObject*, const char*)’:
.../turtlebot/src/turtlebot_apps/software/pano/pano_py/src/pano_cv/opencv.cpp:60:40: error: ‘PyString_Check’ was not declared in this scope
   if (m->data && PyString_Check(m->data))
                                        ^
.../turtlebot/src/turtlebot_apps/software/pano/pano_py/src/pano_cv/opencv.cpp:63:44: error: ‘PyString_AsString’ was not declared in this scope
       char *ptr = PyString_AsString(m->data) + m->offset;
                                            ^
.../turtlebot/src/turtlebot_apps/software/pano/pano_py/src/pano_cv/opencv.cpp: In function ‘cv::Mat pano_py::{anonymous}::convert_from_cviplimage(PyObject*, const char*)’:
.../turtlebot/src/turtlebot_apps/software/pano/pano_py/src/pano_cv/opencv.cpp:90:31: error: ‘PyString_Check’ was not declared in this scope
   if (PyString_Check(ipl->data)) {
                               ^
.../turtlebot/src/turtlebot_apps/software/pano/pano_py/src/pano_cv/opencv.cpp:91:50: error: ‘PyString_AsString’ was not declared in this scope
     cvSetData(ipl->a, PyString_AsString(ipl->data) + ipl->offset, ipl->a->widthStep);
```

**Comment by bit-pirate** [comment]
Please also state, what system you are running on and other important information, such as the python version you are using.

**Comment by ccard** [comment]
i am using:
- ubuntu 14.04 (32 bit)
- ROS indigo
- python 2.7.6 (installed from source not apt-get), python 3 and 3.4 where installed when ros was installed and i can't remove them without also removing ros indigo
  also i found that when i was compiling (catkin_make) it was linking to libpython3.0my.so so i removed based on a  suggestion from this [post](https://bugs.launchpad.net/opencog/+bug/1063039).  but now when i compile it outputs:
  `-- Found PythonLibs: /usr/local/lib/libpython2.7.a (found version "3.3.0")`
  and still fails with the output as previously posted.
  also all of my environmental variables seem to be correct.

**Comment by stonier** [comment]
Looks rather like some python functionality is missing or not found.

A first step id suggest is checking that it works with trusty and a system install of python 2.7. If that does you can start checking what is different with your source install.

**Comment by ccard** [comment]
I resolved the issue it turns out that there where left over programs from my upgrade from 12.10 to 14.04 doing a completely fresh install of ubuntu 14.04 fixed the problem.  Thanks for your help
