### ISSUE TITLE
turtlebot_follower/launch/follower.launch has on small XML syntax error

### ISSUE THREAD

**Issue by howlong** [turtlebot/turtlebot_apps#127]
The original line 6 is:  " <group unless="$(arg simulation)"/> "
which results error when executing "$ roslaunch turtlebot_follower follower.launch ":
"Invalid roslaunch XML syntax: mismatched tag: line 41, column 4
The traceback for the exception was written to the log file"

After the modification of " <group unless="$(arg simulation)"> ", 
everything works fine

**Comment by jihoonl** [comment]
/ shouldn't be there ..fixed.

**Comment by muhammad96** [comment]
what is the change that was made here??
