### ISSUE TITLE
A new Package does not build when turtlebot_teleop is a dependancy

### ISSUE THREAD

**Issue by anuraj-rp** [turtlebot/turtlebot_apps#128]
Hi,
I am trying to build a custom package with turtlebot_teleop as dependency. But the build fails with the following message. I am using ros-hydro on ubuntu 12.04.

``` bash
CMake Error at /opt/ros/hydro/share/turtlebot_teleop/cmake/turtlebot_teleopConfig.cmake:141 (message):
  Project 'turtlebot_custom' tried to find library 'turtlebot_teleop'.  The
  library is neither a target nor built/installed properly.  Did you compile
  project 'turtlebot_teleop'? Did you find_package() it before the
  subdirectory containing its code is included?
Call Stack (most recent call first):
  /opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:75 (find_package)
  turtlebot_custom/CMakeLists.txt:7 (find_package)


-- Configuring incomplete, errors occurred!
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
```

I looked into the CMakeLists.txt of turtlebot_teleop. When I comment the LIBRARIES option in catkin_package() it builds successfully. I also don't see any source code in the turtlebot_teleop which would generate a library. I am new to catkin build system. Am I missing something here??

**Comment by jihoonl** [comment]
If you have installed turtlebot_teleop deb, it only installs library. It does not install source code. What do you want to do in turtlebot_custom?

**Comment by tfoote** [comment]
Closing for now. If you have more questions please ask on http://answers.ros.org
