### ISSUE TITLE
Velocity Command Manager

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot_apps#15]
Been talking about having a manager to control various inputs into /cmd_vel that allows you to prioritise incoming commands (obstacle avoidance control over teleop for instance) and also do velocity smoothing before relaying onto /cmd_vel. 

Joystick teleop/keyboard teleop/android teleop/test motion patterns make the robot dance right now, which is fun, but it doesn't look or feel great teleop'ing it like that.

**Comment by stonier** [comment]
Generalise the one we use on our other robots and put it into an open stack.

**Comment by bit-pirate** [comment]
I think we can close this, since we add this functionality in [yujin_ocs/cmd_vel_mux.](https://github.com/yujinrobot/yujin_ocs/tree/master/cmd_vel_mux).
