### ISSUE TITLE
do we really want to depend on ecl?

### ISSUE THREAD

**Issue by mmwise** [turtlebot/turtlebot_apps#16]
https://github.com/turtlebot/turtlebot_apps/blob/master/turtlebot_panorama/manifest.xml

**Comment by stonier** [comment]
Oh, there...no. It shouldn't be. That one has snuck past me and I'll check it out.

We have the ecl stuff as a dependency of kobuki_driver though. I had thought about replacing it's components with boost, but in the end, ecl is much lighter and much less trouble for us to support for windows or cross compiling (and installations of). We've been using it internally for the very small arm cores for a while. It seems alot, but it's mostly small packages and many of them just a couple of headers.

They're building already in groovy (legacy) and I'll be catkinizing them very shortly so we can look at a windows kobuki build.
