### ISSUE TITLE
Turtlebot_navigation to Nvidia jetson

### ISSUE THREAD

**Issue by Manujaya94** [turtlebot/turtlebot_apps#168]

**Comment by Manujaya94** [comment]
Hi , I am using Nvidia Jetson TX2 to my indoor robot , Can I use the turtlebot_Navigation to autonamous navigation   to my indoor robot
 Thank you

**Comment by tfoote** [comment]
yes, the turtlebot navigation stack is designed to be flexible and extendable for other robots.

If you have more questions please ask on answers.ros.org following our support guidelines. http://wiki.ros.org/Support Please make sure to read through the guide for asking good questions such as making sure to have enough details.
