### ISSUE TITLE
Update turtlebot_teleop

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot_apps#24]
Just had a look at the teleop app and was surprised by the dependencies.
I can't find a reason, why it should depend on map_store and mjpeg_server (check includes and launch files).
Anybody knows why?

Furthermore, we should find a way to merge kobuki_keyop and turtlebot_teleop.

**Comment by stonier** [comment]
These were for the app manager apps, now in turtlebot_core_apps. I shifted these deps there: 05ae86812d8b4f140916f03209a113de505d2e57

Jorge - when the image nodelet stuff is working properly, can you check why the turtlebot_core_apps/android_teleop is using mjpeg server?
