### ISSUE TITLE
Merge in kobuki apps

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot_apps#3]
Most are the same, we have a different chirp.

Not going to worry about doing anything different for turtlebot2 till we have a better gateway model/android pairing setup a few months down the line (us, austin and osrf).

Don't forget to update the app manager installed lists - turtlebot/turtlebot/issues/15

**Comment by jihoonl** [comment]
e640fd9118ba6c1f15d4942b81946b85b53ce5c4

Done

**Comment by stonier** [comment]
Is chirp chirping (or mooing)?

**Comment by jihoonl** [comment]
Yeah working! :D
