### ISSUE TITLE
Review turtlebot apps

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot_apps#32]
Now openni is somewhat finalised and seems to be working ok, run through all the launchers in turtlebot_apps, upgrade them and make sure they're working well.
- <del>teleop (turtlebot_teleop and android)</del>
- <del>navigation (turtlebot_navigation and android)</del>
- <del>follower (turtlebot_follower and android)</del>
- <del>panorama (turtlebot_panorama and android)</del>
- <del>auto docking (android, redefine app lists for this too)</del>
- <del>actions (turtlebot_actions)</del>
- <del>interactive_markers</del>

**Comment by stonier** [comment]
Android teleop had a facelift 9c11cb36862f99ec0a48b06c8580726f3f086b22, but is still not publishing compressed images. I suspect there's a problem with the image_transport package - it's not discovering plugins, even if they're installed.

Following the issue here: https://github.com/ros-perception/image_common/issues/6

**Comment by LucidOne** [comment]
On 12/28/2012 11:28 AM, Daniel Stonier wrote:

> Android teleop had a facelift 9c11cb36862f99ec0a48b06c8580726f3f086b22, but is still not publishing compressed images. I suspect there's a problem with the image_transport package - it's not discovering plugins, even if they're installed.
> 
> Following the issue here: https://github.com/ros-perception/image_common/issues/6
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/turtlebot/turtlebot_apps/issues/32#issuecomment-11735321

I'm not sure if this is the right place but I'm going to -1 the new icon.
I think we should be aiming for something that is more stylistically
compatible with the default android icons instead of a glossy circle.

**Comment by stonier** [comment]
The default android icons have a style?

**Comment by stonier** [comment]
Compressed images in android teleop now working - robot battery isn't though.

**Comment by chadrockey** [comment]
Well, ideally they will fit the following:
http://developer.android.com/guide/practices/ui_guidelines/icon_design_launcher.html

I believe this issue is about the turtlebot app interface?  Or app manager
interface?  The icons should match the Android icons to avoid confusion.

If this is about the apps themselves, ticket here and maybe we can update
them at or after the hackathon:

https://github.com/ros-android

https://github.com/ros-android-pr2

**Comment by LucidOne** [comment]
This is what I see as looking odd.
https://github.com/turtlebot/turtlebot_apps/blob/9c11cb36862f99ec0a48b06c8580726f3f086b22/turtlebot_core_apps/apps/android_teleop/android_teleop.png

**Comment by stonier** [comment]
Not for the android apps themselves - just the app manager interface to give them something more consistent, stylish within the master chooser. The internal picture does match the android icons - where there is an android icon (chirp, joystick teleops dont).

**Comment by stonier** [comment]
[screenshot](http://files.yujinrobot.com/images/tmp/appchooser_icons.png)

As I said before, these are the app manager icons only, not the android icons. They match in the sense that they use the same icon inside (my galaxy tab does a similar thing putting a backdrop on each icon when I hit the applications menu). I'm quite happy for a good redesign if someone will step up to do so - I just had a fleeting desire to use icons that looked a bit more than something copy/pasted as an afterthought.

**Comment by stonier** [comment]
Robot battery in android fixed by https://github.com/turtlebot/turtlebot/commit/b4d5bfef5e78444b0243fa937e565daa615c6c68

**Comment by stonier** [comment]
Apart from a deceleration smoothing problem (https://github.com/yujinrobot/yujin_ocs/issues/6), teleops are working well.

**Comment by stonier** [comment]
navigation on pc and android sorted in 97fe7ce25871c421b1351e6375968b13a71ba95a. Also reinserted the logitech controller and updated the wiki for the other controllers.

**Comment by stonier** [comment]
Just panorama app bug and android app upload remaining. See #38.
