### ISSUE TITLE
Joystick Teleop

### ISSUE THREAD

**Issue by LucidOne** [turtlebot/turtlebot_apps#35]
The button for the deadman switch seems to have changed.
On the logitech joystick it now maps to the left 'joystick pushed' button, which is about the worst possible option.

**Comment by stonier** [comment]
Might have been my naive changes over christmas. We dont have a logitech joystick, so please send a pull request with preferred deadman params.

**Comment by stonier** [comment]
Changed the xbox360 for us: 7f968e8a40e4310a33f4a560d3b3b0926eead0d7

Please update the logitech and test when you can bill.

**Comment by LucidOne** [comment]
We need to rename rumblepad2_teleop.launch to logitech_teleop.launch
It works with the new F### series joysticks from logitech and the Rumblepad2 was made by Logitech and is discontinued.

**Comment by stonier** [comment]
Does it work for all logitech joystics?

**Comment by LucidOne** [comment]
On 02/11/2013 02:35 AM, Daniel Stonier wrote:

> Does it work for all logitech joystics?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/turtlebot/turtlebot_apps/issues/35#issuecomment-13370719..

It works for all wireless joysticks they currently sell.
I think that is close enough.

**Comment by stonier** [comment]
2741efa0a5765c04285077d6c28af182ec41aa7c
