### ISSUE TITLE
Mongodb

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot_apps#4]
See if we can directly use ubuntu's mongodb package now.

I note that it's use is commented out in the mongodb ros package - it uses an internally compiled (downloaded?) package.

**Comment by stonier** [comment]
Another note - it bugs out if you have the system /etc/init.d/mongodb running.

I think I've read that it's also a good idea not to run two mongodb instances side by side since they have a policy of grabbing as much ram as they can find. Check if that's the reason for it bombing before.

**Comment by jihoonl** [comment]
In my investigation, only one mongodb is running all the time. 
wrapper.py in mongodb ros-pkg attempts to bind the same address as the /etc/init.d/mongodb one and it kills itself if the address is binded already. So there is no chance running two instances of mongodb.

Also, I have tested the apps with launch file which mongodb rospkg is commented out and worked fine if mongodb instance is running already.

**Comment by jihoonl** [comment]
So my conclusion is we can directly use ubuntu's mongodb package

**Comment by stonier** [comment]
Ok, closing for now.
