### ISSUE TITLE
Catkinizing for Hydro

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot_apps#41]
Looking through the stack deps, I have found the below stacks/packages which haven't been catkinized yet. We would need to contact the maintainers to check, if and when these get catkinized.
- map_store [(kforge)](https://kforge.ros.org/mapstore/hg): currently no development happening
- navigation [(github)](https://github.com/ros-planning/navigation/tree/hydro-devel): looks like they are preparing
- slam_gmapping [(github)](https://github.com/ros-perception/slam_gmapping): currently no development happening

That's it I would say.

**Comment by bit-pirate** [comment]
According to Jorge, the navigation stack is currently under heavy development and there are plans to get it catkinized for Hydro.

For map_store and slam_gmapping I have contacted Dave Hershberger. There are no official maintainers for these stacks and he has been the last one committing to each of them. Let's see, if there are any plans for catkinizing these. Maybe we have to allocate some time to help on this.

**Comment by mikeferguson** [comment]
Just a note, slam_gmapping will be a fun one to catkinize, since it uses the old "download a tarball from wg, and build it", which I don't think exists in catkin....

**Comment by chadrockey** [comment]
Ugh, yeah those are terrible.  Sicktoolbox used automake and the tarball method.  I ended up forking it entirely to github and just creating a cmake version that included all of the patches.

**Comment by mikeferguson** [comment]
Yeah, I think that was the same thought for gmapping. Also just a note, before Vincent departed Willow, he did talk with the gmapping authors and got their blessing to create a github fork, hosted here: https://github.com/ros-perception/gmapping

**Comment by jack-oquin** [comment]
Segbot has similar conversion requirements.

**Comment by hershwg** [comment]
@vrabaud Do you have an opinion on the catkin-ization of  https://github.com/ros-perception/gmapping ?

Is there a problem with making it a catkin project directly?

http://ros.org/wiki/bloom/Tutorials/ReleaseThirdParty This bloom doc makes it sound like it's not that hard to release a non-catkin package with bloom in such a way that it plays nicely with catkin.  Sounds like all we need to do is add a package.xml file and modify the makefiles such that it gets installed.

I don't have feelings for this one way or another, I just want us to find the easiest way forward.

I think map_store should be easy to catkinize.  I can probably get to it in the next week or two.

**Comment by jack-oquin** [comment]
@piyushk and I released a patched-up [libfreenect](https://github.com/ros-drivers-gbp/libfreenect-release) as a 3rd-party package. It was more difficult than we expected, but seems to work OK now.

It is a reasonable solution for the kind of problem you describe.

**Comment by piyushk** [comment]
I'll add my two cents here. IMO the easiest way forward is @hershwg's first suggestion of making the fork a catkin project directly. gmapping has not changed in the last 5 years, and it's not clear if a 3rd party release that maintains ties to the original SVN repository has any benefit. Additionally, in terms of SLAM approaches, it is pretty old. I am not sure how relevant it will be a couple of years down the line.

When @jack-oquin and I patched [libfreenect](https://github.com/ros-drivers-gbp/libfreenect-release), it had CMake set up already and the patches were relatively minor. There were subsequent problems in releasing those patches into both the groovy and hydro release. Given that gmapping will require far more significant patches to setup CMake, and it's not clear if anybody has time to maintain the stack - I am not sure if doing a 3rd party release is the best option.

**Comment by bit-pirate** [comment]
Out of curiosity, is there an alternative to gmapping out there - something less outdated and easier to be catkinized?

**Comment by rgariepy** [comment]
Karto and Hector are similar and not difficult to work with, not sure how
hard they are to catkinize. I had someone here do a comparison study
throughout our office, but it's not yet done to my standards. In general,
gmapping seems to be the slowest, middling in robustness, and awful wrt
memory usage.

-Ryan

**Comment by tfoote** [comment]
There are two parts to gmapping which are currently conflated.  There's the
external 3rdparty package, and then the ROS interface.

Hector is probably the best alternative.  I expect it will be converted in
the future.  But I believe the authors are pretty busy at the moment with
another project.

**Comment by vrabaud** [comment]
the gmaping fork we created on GitHub (with Giorgio's approval) is just the 3rd party one. We could catkinize it if necessary. And it include the patches (and more) that we did in the hacky rosmake version.
Now, there is still the slam_gmapping one: that should be trivial too. Let me try to do both tonight.

**Comment by jack-oquin** [comment]
I think we do want a catkinized version of gmapping. Despite its age and lack of activity, it has been useful for many in the ROS community.

The main reason Piyush and I used bloom 3rd-party packaging for **libfreenect** is because we did _not_ want to take over maintaining it. We wanted to keep the option of replacing it with some newer "official" version, should the upstream developers choose to release one. We check out a more recent level from the upstream repository that has additional fixes we need. Then we add package.xml as a patch. Unfortunately, many more patches are needed to get things working.

If **gmapping** is _not_ actively maintained any longer, it will almost certainly be easier to maintain the package.xml, CDMakeLists.txt and other ROS files directly in the source repository. We can declare it "end-of-life" and only change it to fix bugs.

**Comment by vrabaud** [comment]
sounds good, Should I merge slam_gmapping and gmapping ? make more sense to me to keep them as two packages.

**Comment by mikeferguson** [comment]
I would keep them as two separate packages -- it's more inline with the ROS "thin-wrapper" ideal...

**Comment by piyushk** [comment]
+1 for separate packages. The github gmapping repository will be useful if someone wants to use gmapping through cmake. Since it should be relatively easy to patch this upstream repository, the third party release (aka ros-<distro>-gmapping) should be relatively painless.

In case you don't have a reference already, take a look at [libsegwayrmp](https://github.com/segwayrmp/libsegwayrmp) and [segway_rmp](https://github.com/segwayrmp/segway-rmp-ros-pkg). It's a bit cleaner than libfreenect. The corresponding release repos are under the same organization.

**Comment by vrabaud** [comment]
ok guys, I kept them separate  and I catknized them. This is a first draft: gmapping + slam_gmapping compile for me  on Ubuntu Raring gcc 4.8.
slam_gmapping is fully catkinized.
gmapping is not: there are some folders that are just for GUI's I think. I'll do that later.

I'd be more than happy to have another official maintainer as I now have 51 packages to maintain :)

**Comment by bit-pirate** [comment]
@hershwg already started catkinizing [map_store](https://github.com/ros-planning/map_store).

**Comment by mikeferguson** [comment]
FYI https://github.com/ros-perception/slam_gmapping/issues/6

**Comment by hershwg** [comment]
OK, https://github.com/ros-planning/map_store is catkinized and passes its test.  I haven't actually used it, so please let me know if there are https://github.com/ros-planning/map_store/issues .  I'll do a release if it works for you.

**Comment by bit-pirate** [comment]
@corot let's test the map_store some time soon, so that @hershwg can proceed with the release.

**Comment by corot** [comment]
map_store works like a dream.....

**Comment by hershwg** [comment]
@corot thanks!  map_store release process is done on my end, now we wait for build farm etc.

**Comment by corot** [comment]
All catkinized and ready to release
