### ISSUE TITLE
turtlebot_rgbdslam should probably be a standalone app package

### ISSUE THREAD

**Issue by mmwise** [turtlebot/turtlebot_apps#42]
By adding this package to turtlebot_apps the dependency tree becomes VERY large and it depends on currently unreleased code ccny_rgbd which is currently not called out in the package manifest but should be.

**Comment by jihoonl** [comment]
I expected ccny rgbd slam to be catkinized at some point. which means that only rgbd slam would have large dependency. 

But I see your point too. I will remove it from the repo.

**Comment by jihoonl** [comment]
newapp branch is deleted.
