### ISSUE TITLE
panorama: what is this app/pano_img_topic param?

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot_apps#46]
And where is it used?

**Comment by corot** [comment]
Is not used by now: Android apps had harcoded topics names (only the app namespace is dynamic).

New app manager should fix this somehow.

Tracked here: https://github.com/robotics-in-concert/rocon_app_platform/issues/58

**Comment by stonier** [comment]
Can't change the whole app hardcoding now, but should at least remove the redundant rapp information to stop it from being confusing. e.g. https://github.com/turtlebot/turtlebot_apps/blob/hydro-devel/turtlebot_core_apps/rapps/panorama/panorama.rapp

**Comment by bit-pirate** [comment]
Let's remove this unused information from all rapp files for now and add it again, once it is supported by the apps and app manager.
