### ISSUE TITLE
Make turtlebot apps work with Android apps

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot_apps#47]
Our efforts of getting rid of absolute namespace don't work well with the app manager namespacing. Use absolute namespaces where need and fix everything else.

Apps needing fixing:
- [x] turtlebot_follower
- [x] panorama
- [x] teleop
- [x] Auto dock
- [x] Make a Map
- [x] Map Nav
- [x] Map Manager

**Comment by bit-pirate** [comment]
Let's fix them using absolute namespaces for now and improve them once we have capabilities. Follow this issue for that: https://github.com/turtlebot/turtlebot_apps/issues/48

**Comment by bit-pirate** [comment]
The navigation apps are mostly done, but without a working map view I couldn't test everything, e.g. build and navigate a map. Once issue #50 is resolved, we can proceed with testing and fixing them.

**Comment by corot** [comment]
Here we go!

**Comment by stonier** [comment]
Just releases to go ;)

**Comment by stonier** [comment]
And the tf_change fix in rosjava.

**Comment by corot** [comment]
All up and running now; we keep the tf_change in issue #68.
