### ISSUE TITLE
Why do we look like smurfs in android teleop?

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot_apps#5]
Something's either up with the kinect camera or our xoom.

**Comment by LucidOne** [comment]
BGR -> RGB I don't understand why but the OpenNI driver changed at some
point.

**Comment by stonier** [comment]
Hmm...easily fixable without recompiling the android app?

**Comment by yhju** [comment]
Daniel, have you tried another kinect?

**Comment by stonier** [comment]
No - though if bill's right, it'll be the same.

**Comment by chadrockey** [comment]
Hey, I looked into this.

It looks like there was a regression in image_transport_plugins.  As of version 1.8.7-0, this should be fixed.
http://www.ros.org/debbuild/groovy.html

Today, 12/10/12, the latest available from shadow-fixed and public is 1.8.5-1.

Commit that should fix it:
https://github.com/ros-perception/image_transport_plugins/commit/01258e08d15f375629dce3f87b43ded938b33443

**Comment by stonier** [comment]
Looks good now.
