### ISSUE TITLE
make_a_map: map view doesn't work

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot_apps#50]
Usually just shows a black picture and sometimes some orange artefacts.

**Comment by bit-pirate** [comment]
When this issue is resolved, make sure that the navigation android apps (make a map, map nav, map manager) work well together with the rapps (namespace, topic flipping etc.) and mark the related. tasks at #47 as done.

**Comment by bit-pirate** [comment]
Follow this issue for details: https://github.com/ros-java/android_apps/issues/21

**Comment by stonier** [comment]
What works...

```
roslaunch turtlebot_bringup minimal_with_appmanager.launch
roslaunch turtlebot_rviz_launchers view_navigation.launch
```

**Comment by corot** [comment]
All working like a dream now.
