### ISSUE TITLE
auto_docking: shut down app when robot is docked

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot_apps#53]
Would be nice, if the app shuts down automatically, once the robot is docked (being charged). The chirp app does that, but I am not sure what is needed for auto docking to behave similar.

**Comment by stonier** [comment]
The robot app stops. Does the robot docking app not stop once its docked?

**Comment by bit-pirate** [comment]
Correct. The robot app stays active and one has to manually stop it.

**Comment by stonier** [comment]
That's a bit odd - I would have thought the app would terminate itself on success.

@yhju any special reason for this?

**Comment by yhju** [comment]
AutoDockingActionClient.py is simple action client.

It will be terminated automatically, when the result arrive from the action
server.

**Comment by stonier** [comment]
Marcus was asking about whether the robot app terminates. I think you are saying the action client terminates - correct? The robot app doesn't.

**Comment by stonier** [comment]
I think from reading old ros users, it might not have api to shut down the nodelet from inside the nodelet. 

If that is the case, the client should call the nodelet manager service to unload the nodelet, then shut down.

**Comment by tfoote** [comment]
That is correct.  Your only way is to unload it using the service call to
the manager which isn't so great.

**Comment by bit-pirate** [comment]
Jorge, just told me about roslaunch's `required` attribute (http://www.ros.org/wiki/roslaunch/XML/node#Attributes). So, it might be enough to set `required = true` for the client, since the client shuts down, once the robot is docked.

Btw @tfoote, I believe `required = true` is **not** the default as claimed in the wiki, right?

**Comment by stonier** [comment]
Oh, didn't know about that.

I think a simple experiment should be informative. Another possible item to check is whether the terminology 'dies' as written on the wiki page refers to the node process finishing in general, finishing with a segfault or finishing with an error value.

**Comment by yhju** [comment]
Done by a2c7caa41cd9560f915f0fef4e1adf46832fbc05.
