### ISSUE TITLE
turtlebot_teleop/src/turtlebot_joy.cpp: bug or undocumented feature?

### ISSUE THREAD

**Issue by MartinPeris** [turtlebot/turtlebot_apps#71]
Hi there,

the variable "bool deadman_pressed_" on turtlebot_teleop/src/turtlebot_joy.cpp is never initialized on the constructor. This causes "deadman_pressed_" to be randomly initialized. Some times it will be initialized as "true" causing "TurtlebotTeleop::publish()" to publish a cmd_vel full of zeros until a button on the joystick has been pressed for the first time and "deadman_pressed_" is set with the correct value.

This almost drove me crazy, when using turtlebot_joy together with the navigation stack, as the navigation stack was sending cmd_vel commands to the motor controller and the turtlebot_joy node, was sending "stop" commands at the same time, causing the robot to move irregularly.

The solution is to initialize deadman_pressed_ to false on the TurtlebotTeleop constructor.

**Comment by chadrockey** [comment]
@MartinPeris I think you're correct.  It should default to "false" or "don't send command".

**Comment by MartinPeris** [comment]
The patch has been merged. Closing this issue. Thank you all
