### ISSUE TITLE
Panorama App

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot_apps#8]
Resurrect our really old kobuki panorama app, let's make it official if we can.

**Comment by jihoonl** [comment]
TODO list:
1. appify
2. change bgr to rgb format. 
3. improve panorama quality.

**Comment by jihoonl** [comment]
Appify(DONE) 
- listed in turtlebot_bringtup/apps/turtlebot_apps.installed.
- app files in turtlebot_panorama/app
- tested
- Still it requires front-end interface

59198baffc4f8071284d97e6faa2d30f96d1faf5

**Comment by jihoonl** [comment]
Another TODO:
Develop web App frontend

**Comment by jihoonl** [comment]
1. appify
2. change bgr to rgb format. 
3. improve panorama quality.
   (DONE)

d06d8a70c12ede9ae3b9a06fbd06074141aace0d

App frontend is left

**Comment by stonier** [comment]
Can you make a note of what was important for quality?

**Comment by stonier** [comment]
- Turned out that moving really slowly doesn't introduce much blur.
- Taking alot of photos helps it.

Jihoon has two programs for both modes, continuous and start/stop/capture/rinse/repeat.
