### ISSUE TITLE
Release turtlebot_teleop bug fixes into Hydro

### ISSUE THREAD

**Issue by chadrockey** [turtlebot/turtlebot_apps#81]
There are a few important bug fixes that need released into Hydro:

https://github.com/turtlebot/turtlebot_apps/commit/ca9b69ff408a236f6b62e1e81eebd79801dba5ec

https://github.com/turtlebot/turtlebot_apps/commit/c1b9856058b459428163033fa46ee77a48944a09

The last release was October 13, 2013.

Is there anything blocking a release?  I think these are reasonable fixes that can be accepted without breaking anyone's workflow.

**Comment by jihoonl** [comment]
will do it today.

**Comment by bit-pirate** [comment]
@jihoonl this is done, no?

**Comment by jihoonl** [comment]
done.
