### ISSUE TITLE
Unused keyop cpp file

### ISSUE THREAD

**Issue by chadrockey** [turtlebot/turtlebot_apps#85]
It looks like this file isn't compiled or used?

If it isn't supported or executable, it should probably be removed.

https://github.com/turtlebot/turtlebot_apps/blob/hydro/turtlebot_teleop/src/turtlebot_key.cpp

**Comment by bit-pirate** [comment]
Interesting find. Looks like keyboard teleop is implemented twice and only the python version is used at this moment.

+1 to clear this out (either use the C++ or Python version).

**Comment by jihoonl** [comment]
I will see this when I have time.

**Comment by stonier** [comment]
:+1: to clearing.

**Comment by jihoonl** [comment]
cleared.
