### ISSUE TITLE
Rename turtlebot_core_apps

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot_apps#86]
In order to stick to one name for robot/rocon apps through all packages and stacks, I suggest to rename `turtlebot_core_apps` to either to `turtlebot_core_rapps` or just `turtlebot_rapps`.

Thoughts (@stonier, @jihoonl)?

**Comment by stonier** [comment]
:+1:

**Comment by stonier** [comment]
We should also rename the rapps away from the `android_xxx` forms. That confused people and these rapps aren't actually android specific. Leaving this open till that is done.

**Comment by kentsommer** [comment]
@stonier, this can probably be closed out since #100 was merged.

**Comment by jihoonl** [comment]
Done.
