### ISSUE TITLE
amcl_demo footprint error - specify three points [indigo]

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot_apps#92]
Getting this

```
[ERROR] [1402393990.853257898]: You must specify at least three points for the robot footprint, reverting to previous footprint.
```

Is it a meaningful error? I haven't had time to explore yet, so this is a stub till I know.

**Comment by mikeferguson** [comment]
Are you sure that is coming from AMCL? I think it's actually coming from move_base, specifically costmap_2d. Is it also only happening the second time you start navigation with the same roscore up? If so, it's probably this bug: https://github.com/ros-planning/navigation/issues/206

**Comment by stonier** [comment]
@mikeferguson I'm still yet a one week navistack newbie, so my references are likely to be a little wayward still! I used amcl here simply because it was occurring when starting the turtlebot amcl_demo.

And yes, just tested it and the situation you described is exactly what is happening.

**Comment by mikeferguson** [comment]
@stonier my current hack is to put that "delete" on the parameters in the namespace. The footprint stuff is fairly convoluted and I haven't had time to find a fix yet.

**Comment by stonier** [comment]
Yeah, I noticed that. I'll test it shortly.

**Comment by mikeferguson** [comment]
FYI, this has probably been fixed by https://github.com/ros-planning/navigation/pull/343

**Comment by jihoonl** [comment]
Aight Thanks.
