### ISSUE TITLE
[amcl_demo] robot_radius infestation

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot_apps#94]
Seems the costmaps and inflation layers both have `robot_radius` dynamically reconfigurable parameters. The costmap parameter is 0.18 and inflation layer parameter is 0.46.
- What is the meaning for each parameter?
- 0.46 is a wierd value for this.

**Comment by mikeferguson** [comment]
0.46 is, I believe, the default from the PR2. Most of the navigation stack defaults are from the PR2.

**Comment by stonier** [comment]
Thanks fergs.

Looks like it's set by default by the [inflation plugin](https://github.com/ros-planning/navigation/blob/86c6aa6f6f72eb4cc8ad32a3f23fc3458b2a6894/costmap_2d/cfg/InflationPlugin.cfg#L12).

Odd thing though, it doesn't seem to have any effect. Local obstacles in rviz have a collision zone of 0.18 still, not 0.46 and dynamically reconfiguring it also doesn't seem to have any effect.
