### ISSUE TITLE
pano_cv/opencv.cpp panorama integration silent fail  [indigo]

### ISSUE THREAD

**Issue by kentsommer** [turtlebot/turtlebot_apps#98]
In the functon `convert_from_cvmat`, both the call `PyString_Check(m->data)` and `PyObject_AsWriteBuffer(m->data, &buffer, &buffer_len)` will cause the `pano_server` to die silently. m->data looks like it is returning an int in hex while m is simply a pointer to a location in memory (The last debug print I ran returned: "m->data print: 0x3" and "m print: 0x245a250")

PyObject_AsWriteBuffer is deprecated in python2, however, it doesn't seem to be the reason for the issue above. 

datatype passed into `convert_from_cvmat` is numpy.ndarray. My best guess as to why the above behavior is being exhibited is that both `PyString_Check` and `PyObject_AsWriteBuffer` cannot handle the input type and just quit silently. 

_**Steps to reproduce on indigo**_

On turtlebot run:
- roslaunch turtlebot_bringup minimal.launch
- roslaunch turtlebot_panorama panorama.launch --screen
- rosservice call turtlebot_panorama/take_pano 1 360.0 30.0 0.3

Will run until it hits one of the two above function calls and then the process will die printing:
`[pano_server-6] process has died [pid 5853, exit code -11]`

**Comment by jihoonl** [comment]
Can you link the file which causes the problem?

**Comment by jihoonl** [comment]
https://github.com/turtlebot/turtlebot_apps/blob/indigo/software/pano/pano_py/src/pano_cv/opencv.cpp#L52

**Comment by jihoonl** [comment]
@stonier cmake_modules dependency would help this issue? Since it is using numpy?

**Comment by kentsommer** [comment]
**Progress!** 

In `capture_server.py` I added a conversion from numpy.ndarray to cv2.cv.cvarray. That image can be passed to pcv.convertCvMat2Mat which does the final conversion to cv::Mat before finally passing the fully converted image to the stitch engine. 

The turtlebot will now rotate while taking pictures and publishing them (verified). 

**Current issues** 
- The pano_server still dies silently after finishing taking pictures and completing its rotation.
  - Appears to be an bug inside the stop() function in `capture_server.py`
- Currently is taking less pictures than it should with the given parameters.

**Comment by kentsommer** [comment]
**Fixed/Updated**

See pull request #99 for more information. Closing this out since fix has been merged in #99
